# Generated by Django 4.2.16 on 2025-05-22 07:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_user_type_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_index', models.IntegerField(help_text='The 0-based index of the level completed')),
                ('time_taken', models.IntegerField(help_text='Time taken to complete the level in seconds')),
                ('selected_timer', models.IntegerField(help_text='The timer setting chosen by the user for this attempt (e.g., 30, 45, 60 seconds)')),
                ('wpm', models.IntegerField(default=0, help_text='Words Per Minute achieved in this attempt')),
                ('score', models.IntegerField(default=0, help_text='Final score achieved in this attempt')),
                ('stars_earned', models.IntegerField(default=0, help_text='Number of stars earned (0-3)')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='typetest_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'TypeTest Progress',
                'ordering': ['-completed_at'],
            },
        ),
    ]
