# Generated by Django 4.2.16 on 2025-05-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_typetestprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='typetestprogress',
            name='all_words_completed',
            field=models.BooleanField(default=False, help_text='Whether the user completed all words in the level'),
        ),
    ]
