# Generated by Django 5.1.4 on 2025-05-11 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_photo',
        ),
    ]
