# Generated by Django 5.1.4 on 2025-05-11 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hearts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hints',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
