# Generated by Django 5.1.4 on 2025-05-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_hearts_user_hints_user_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hearts',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='hints',
            field=models.IntegerField(default=3),
        ),
    ]
