# Generated by Django 4.2.16 on 2025-05-24 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_typetestprogress_all_words_completed'),
        ('api', '0006_alter_user_hearts_alter_user_hints'),
    ]

    operations = [
    ]
