# Generated by Django 4.2.16 on 2025-05-28 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_insertionsortresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnakeGameProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='The level number (1-5)')),
                ('score', models.IntegerField(default=0, help_text='Score achieved in this attempt')),
                ('food_eaten', models.IntegerField(default=0, help_text='Number of food items eaten')),
                ('time_survived', models.IntegerField(default=0, help_text='Time survived in seconds')),
                ('game_completed', models.BooleanField(default=False, help_text='Whether the user completed the level successfully')),
                ('stars_earned', models.IntegerField(default=0, help_text='Number of stars earned (0-3)')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snake_game_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Snake Game Progress',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'level'], name='api_snakega_user_id_c043af_idx'), models.Index(fields=['user', 'level', 'score'], name='api_snakega_user_id_1efa4f_idx')],
            },
        ),
    ]
