# Generated by Django 5.1.4 on 2025-06-05 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_snakegameprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_heart_regen_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='max_hearts',
            field=models.IntegerField(default=5),
        ),
    ]
