# Generated by Django 5.1.4 on 2025-06-06 05:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_user_last_heart_regen_time_user_max_hearts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hearts_gained_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hearts_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='max_daily_hearts',
            field=models.IntegerField(default=5),
        ),
    ]
