# Generated by Django 5.1.4 on 2025-06-08 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_hearts_gained_today_user_hearts_reset_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='max_daily_hearts',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_hearts',
            field=models.IntegerField(default=10),
        ),
    ]
