# Generated by Django 5.1.4 on 2025-06-08 07:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_max_daily_hearts_alter_user_max_hearts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hearts_reset_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
