# Generated by Django 5.1.4 on 2025-07-22 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_hearts_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiz_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
