# Generated by Django 4.2.16 on 2025-06-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_hearts_reset_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiz_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='quiz_high_score',
            field=models.IntegerField(default=0),
        ),
    ]
