# Generated by Django 4.2.16 on 2025-06-22 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_user_quiz_attempts_user_quiz_high_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='quiz_attempts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='quiz_high_score',
        ),
    ]
