# Generated by Django 4.2.16 on 2025-06-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_user_quiz_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiz_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
