# Generated by Django 4.2.23 on 2025-07-15 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_quiz_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='quiz_attempts',
        ),
    ]
