# Generated by Django 4.2.23 on 2025-07-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_user_quiz_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quiz_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_hearts',
            field=models.IntegerField(default=5),
        ),
    ]
